CREATE OR REPLACE TABLE stg_illinois_grade4 AS
SELECT
    try_cast(report_card_year AS INTEGER) AS report_card_year,
    trim(rcdts) AS rcdts,
    trim(rcdts_formatted) AS rcdts_formatted,
    trim(rcdts_source) AS rcdts_source,
    trim(entity_level) AS entity_level,
    trim(school_name) AS school_name,
    trim(district_name) AS district_name,
    trim(city) AS city,
    trim(county) AS county,
    trim(school_type) AS school_type,
    trim(grades_served) AS grades_served,
    try_cast(grade AS INTEGER) AS grade,
    lower(trim(subject)) AS subject,
    try_cast(proficiency_rate AS DOUBLE) AS proficiency_rate,
    trim(proficiency_status) AS proficiency_status,
    trim(proficiency_metric_version) AS proficiency_metric_version,
    try_cast(participation_rate AS DOUBLE) AS participation_rate,
    trim(participation_status) AS participation_status,
    try_cast(growth_percentile AS DOUBLE) AS growth_percentile,
    trim(growth_status) AS growth_status,
    trim(growth_metric_version) AS growth_metric_version,
    try_cast(school_enrollment AS DOUBLE) AS school_enrollment,
    trim(school_enrollment_status) AS school_enrollment_status,
    try_cast(grade4_enrollment AS DOUBLE) AS grade4_enrollment,
    trim(grade4_enrollment_status) AS grade4_enrollment_status,
    try_cast(pct_iep AS DOUBLE) AS pct_iep,
    trim(pct_iep_status) AS pct_iep_status,
    try_cast(pct_el AS DOUBLE) AS pct_el,
    trim(pct_el_status) AS pct_el_status,
    try_cast(pct_low_income AS DOUBLE) AS pct_low_income,
    trim(pct_low_income_status) AS pct_low_income_status,
    try_cast(mobility_rate AS DOUBLE) AS mobility_rate,
    trim(mobility_rate_status) AS mobility_rate_status,
    try_cast(chronic_absenteeism_rate AS DOUBLE) AS chronic_absenteeism_rate,
    trim(chronic_absenteeism_rate_status) AS chronic_absenteeism_rate_status,
    try_cast(chronic_absenteeism_grade4_rate AS DOUBLE)
        AS chronic_absenteeism_grade4_rate,
    trim(chronic_absenteeism_grade4_rate_status)
        AS chronic_absenteeism_grade4_rate_status,
    trim(source_file) AS source_file,
    trim(source_sheet) AS source_sheet
FROM read_csv(
    '{{ grade4_csv_path }}',
    header = true,
    all_varchar = true,
    null_padding = true
);
