CREATE OR REPLACE TABLE mart_illinois_grade4_school_year AS
SELECT
    report_card_year,
    rcdts,
    rcdts_formatted,
    school_name,
    district_name,
    city,
    county,
    school_type,
    grades_served,
    grade,
    subject,
    CASE subject WHEN 'ela' THEN 'ELA' WHEN 'math' THEN 'Mathematics' END
        AS subject_label,
    proficiency_rate,
    proficiency_status,
    proficiency_metric_version,
    participation_rate,
    participation_status,
    growth_percentile,
    growth_status,
    growth_metric_version,
    school_enrollment,
    school_enrollment_status,
    grade4_enrollment,
    grade4_enrollment_status,
    pct_iep,
    pct_iep_status,
    pct_el,
    pct_el_status,
    pct_low_income,
    pct_low_income_status,
    mobility_rate,
    mobility_rate_status,
    chronic_absenteeism_rate,
    chronic_absenteeism_rate_status,
    chronic_absenteeism_grade4_rate,
    chronic_absenteeism_grade4_rate_status,
    source_file,
    source_sheet
FROM stg_illinois_grade4;
